// Copyright 2026 The Eigenius Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Dockerfile fragments for an R / Bioconductor env image (D55 P3).
//!
//! The substrate's image-build pipeline (D26 §9.2) composes these with a
//! digest-pinned `bioconductor/bioconductor_docker` base and the asset
//! COPYs (driver, cdylib) into a final Dockerfile. Mirrors
//! `eigenius_julia::dockerfile`.
//!
//! ## Version pinning (D55 §6)
//!
//! The `install_packages` step `BiocManager::install`s the named packages
//! at a pinned Bioconductor release. The strong pin is the resulting
//! [`ImageDigest`](eigenius_runtime_substrate::types::ImageDigest), which
//! fixes R + every installed package + transitive dependency
//! cryptographically; the worker reports the *actual* installed versions
//! via the Health RPC. A `renv.lock` `renv::restore` (exact per-package
//! pins, reproducible re-build) is the documented stronger-pin follow-on —
//! generated by `renv::snapshot()` against a first build, then baked.

use std::path::PathBuf;

use crate::conventions::{CDYLIB_IN_IMAGE, DRIVER_IN_IMAGE, MIRROR_IN_IMAGE};
use eigenius_runtime_substrate::image_build::dockerfile::LanguageAssetCopy;
use eigenius_runtime_substrate::image_build::{
    compose_dockerfile, DockerfileSpec, IncludedPackage,
};
use eigenius_runtime_substrate::types::DockerfileFragments;

/// The worker assets the image bakes (and their in-image destinations).
/// The build context materialises the bytes at `language/<source>`; the
/// composer emits `COPY language/<source> <destination>`.
pub fn worker_asset_copies() -> Vec<LanguageAssetCopy> {
    vec![
        LanguageAssetCopy {
            source: PathBuf::from("EigeniusRWorker.R"),
            destination: DRIVER_IN_IMAGE.to_string(),
        },
        LanguageAssetCopy {
            source: PathBuf::from("libeigenius_r_worker.so"),
            destination: CDYLIB_IN_IMAGE.to_string(),
        },
    ]
}

/// Compose the full Dockerfile text for an R env image: the digest-pinned
/// base, the fragments ([`r_dockerfile_fragments`]), and the worker-asset
/// COPYs. Pure (no file I/O), so the recipe is unit-testable without
/// buildah; `build_environment_image` uses it before materialising +
/// building.
pub fn compose_image_dockerfile(base_image_ref: &str, plan: &RImagePlan) -> String {
    let fragments = r_dockerfile_fragments(plan);
    let asset_copies = worker_asset_copies();
    let no_packages: Vec<IncludedPackage> = Vec::new();
    compose_dockerfile(&DockerfileSpec {
        base_image_ref,
        fragments: &fragments,
        included_packages: &no_packages,
        has_mirror: plan.include_mirror,
        language_asset_copies: &asset_copies,
    })
}

/// Inputs to [`r_dockerfile_fragments`].
#[derive(Debug, Clone)]
pub struct RImagePlan {
    /// Bioconductor release the packages are installed from (e.g.
    /// `"3.18"`). Together with the base image digest this fixes the
    /// package versions `BiocManager::install` resolves.
    pub bioc_version: String,
    /// The Bioconductor/CRAN packages to install (the wrapped tools).
    /// Default: limma + fgsea + lme4 + emmeans (the WRN Tier-2 frontier).
    pub packages: Vec<String>,
    /// `true` once a `RPackageMirror` archive is materialised under
    /// [`MIRROR_IN_IMAGE`](crate::conventions::MIRROR_IN_IMAGE) (P4).
    pub include_mirror: bool,
}

impl Default for RImagePlan {
    fn default() -> Self {
        Self {
            bioc_version: "3.18".to_string(),
            packages: vec![
                "limma".to_string(),
                "fgsea".to_string(),
                "lme4".to_string(),
                "emmeans".to_string(),
            ],
            include_mirror: false,
        }
    }
}

/// Dockerfile fragments for an R env image extending a digest-pinned
/// `bioconductor/bioconductor_docker` base.
///
/// `install_runtime` is empty — the Bioconductor base ships R +
/// `BiocManager`. `install_packages` installs the pinned packages.
/// `bootstrap_command` runs the worker driver, whose loop dispatches to
/// limma/fgsea/lme4.
pub fn r_dockerfile_fragments(plan: &RImagePlan) -> DockerfileFragments {
    // Empty package list ⇒ no install step (don't emit a `BiocManager::install`
    // the base may not even have). A base with no packages to add is valid —
    // e.g. a fast e2e baking only the worker.
    let install_packages = if plan.packages.is_empty() {
        vec![]
    } else {
        vec![install_packages_line(plan)]
    };
    DockerfileFragments {
        install_runtime: vec![],
        install_packages,
        install_mirror: install_mirror_lines(plan),
        bootstrap_command: vec!["Rscript".to_string(), DRIVER_IN_IMAGE.to_string()],
    }
}

fn install_packages_line(plan: &RImagePlan) -> String {
    // `c("limma", "fgsea", "lme4")`
    let pkgs = plan
        .packages
        .iter()
        .map(|p| format!("\"{p}\""))
        .collect::<Vec<_>>()
        .join(", ");
    format!(
        "RUN Rscript -e 'BiocManager::install(c({pkgs}), version=\"{}\", update=FALSE, ask=FALSE)'",
        plan.bioc_version
    )
}

fn install_mirror_lines(plan: &RImagePlan) -> Vec<String> {
    if !plan.include_mirror {
        return vec![];
    }
    // The composer COPYs the mirror archive under MIRROR_IN_IMAGE after
    // install_packages; install it from source so the typed-method path
    // (P4) can `library()` it at worker boot.
    vec![format!(
        "RUN Rscript -e 'install.packages(\"{MIRROR_IN_IMAGE}\", repos=NULL, type=\"source\")'"
    )]
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn base_plan_installs_pinned_packages_and_runs_driver() {
        let f = r_dockerfile_fragments(&RImagePlan::default());
        assert!(f.install_runtime.is_empty(), "bioconductor base ships R");
        assert!(f.install_mirror.is_empty(), "no mirror in the base plan");
        assert_eq!(f.install_packages.len(), 1);
        let line = &f.install_packages[0];
        assert!(line.contains("BiocManager::install"));
        assert!(line.contains("\"limma\", \"fgsea\", \"lme4\", \"emmeans\""));
        assert!(line.contains("version=\"3.18\""));
        assert_eq!(f.bootstrap_command, vec!["Rscript", DRIVER_IN_IMAGE]);
    }

    #[test]
    fn empty_package_list_omits_the_install_step() {
        // A base with no packages to add (e.g. a fast e2e baking only the
        // worker) must not emit a `BiocManager::install` the base may lack.
        let f = r_dockerfile_fragments(&RImagePlan {
            packages: vec![],
            ..Default::default()
        });
        assert!(f.install_packages.is_empty());
        // The driver still runs.
        assert_eq!(f.bootstrap_command, vec!["Rscript", DRIVER_IN_IMAGE]);
    }

    #[test]
    fn mirror_plan_adds_install_mirror_step() {
        let f = r_dockerfile_fragments(&RImagePlan {
            include_mirror: true,
            ..Default::default()
        });
        assert_eq!(f.install_mirror.len(), 1);
        assert!(f.install_mirror[0].contains(MIRROR_IN_IMAGE));
        assert!(!f.install_packages[0].contains(MIRROR_IN_IMAGE));
    }

    #[test]
    fn composed_dockerfile_pins_base_installs_packages_and_copies_assets() {
        let base = "bioconductor/bioconductor_docker:RELEASE_3_18@sha256:abc";
        let df = compose_image_dockerfile(base, &RImagePlan::default());
        // Pinned base.
        assert!(df.contains(&format!("FROM {base}")), "composed:\n{df}");
        // Package install step.
        assert!(df.contains("BiocManager::install"));
        // The worker assets are COPY'd to their in-image paths.
        assert!(df.contains(DRIVER_IN_IMAGE), "driver COPY missing:\n{df}");
        assert!(df.contains(CDYLIB_IN_IMAGE), "cdylib COPY missing:\n{df}");
        // The image CMD runs the driver.
        assert!(df.contains("EigeniusRWorker.R"));
    }
}
