// SPDX-License-Identifier: Apache-2.0

//! Bounded admission checks for encoded Loro imports.

use crate::error::{CrdtError, Result};

/// Maximum encoded bytes accepted by the generic CRDT import API.
pub const DEFAULT_MAX_IMPORT_BYTES: usize = 64 * 1024 * 1024;
/// Maximum operations a generic CRDT import may contribute.
pub const DEFAULT_MAX_IMPORT_OPS: usize = 1_000_000;

/// Explicit resource limits for a Loro import.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct CrdtImportLimits {
    /// Maximum raw encoded Loro bytes before metadata parsing or import.
    pub max_bytes: usize,
    /// Maximum operations encoded in the import, including already-known ones.
    pub max_encoded_operations: usize,
    /// Maximum new operations relative to the current oplog version vector.
    pub max_new_operations: usize,
}

impl Default for CrdtImportLimits {
    fn default() -> Self {
        Self {
            max_bytes: DEFAULT_MAX_IMPORT_BYTES,
            max_encoded_operations: DEFAULT_MAX_IMPORT_OPS,
            max_new_operations: DEFAULT_MAX_IMPORT_OPS,
        }
    }
}

/// What an admitted import will and will not contribute.
///
/// Loro's merge silently drops the operations an importing document already
/// knows (`trim_the_known_part_of_change`), which is how idempotent resync
/// works — and also how a peer-id collision discards a healthy client's writes
/// without a trace. The two counts are kept apart here because only their
/// difference distinguishes "this delta advanced the document" from "every
/// operation in this delta was already accounted for".
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ImportAdmission {
    /// Operations encoded in the blob, including ones already known.
    pub encoded_operations: usize,
    /// Operations that are new relative to the importing document's oplog.
    pub new_operations: usize,
}

impl ImportAdmission {
    /// Operations the import carries that the document already had.
    ///
    /// This is the count Loro trims away during merge. A healthy resync trims
    /// its replay prefix and then advances; a fully-trimmed import contributes
    /// nothing at all.
    pub fn trimmed_operations(&self) -> usize {
        self.encoded_operations.saturating_sub(self.new_operations)
    }
}

/// Validate an encoded Loro import before a fork or Loro import can allocate.
///
/// Returns the exact encoded and new operation counts relative to `current`.
/// Metadata is decoded with Loro's authenticated decoder; malformed or
/// regressing per-peer ranges are rejected before any state mutation.
pub(crate) fn admit_import(
    bytes: &[u8],
    current: &loro::VersionVector,
    limits: CrdtImportLimits,
) -> Result<ImportAdmission> {
    if bytes.len() > limits.max_bytes {
        return Err(CrdtError::ImportTooLarge {
            limit: limits.max_bytes,
            actual: bytes.len(),
        });
    }

    let admission = admit_structure(bytes, current)?;
    if admission.encoded_operations > limits.max_encoded_operations {
        return Err(CrdtError::ImportOperationLimitExceeded {
            limit: limits.max_encoded_operations,
            actual: admission.encoded_operations,
        });
    }
    if admission.new_operations > limits.max_new_operations {
        return Err(CrdtError::ImportOperationLimitExceeded {
            limit: limits.max_new_operations,
            actual: admission.new_operations,
        });
    }
    Ok(admission)
}

/// Validate an encoded Loro import this process produced itself.
///
/// Structurally identical to [`admit_import`] — the same authenticated
/// metadata decode, the same rejection of regressing per-peer ranges — but
/// without the size ceilings.
///
/// Those ceilings answer a question that only arises for bytes off the wire:
/// how much work an untrusted peer may make this document do. Applied to
/// locally-generated bytes they instead cap how large a document this library
/// may reload after writing it, which is a different and unintended promise —
/// `export_snapshot` has no bound at all, so a document a healthy process
/// wrote could exceed what the same binary would re-import. Restoring from
/// disk and folding a shallow snapshot back in during compaction are both that
/// case: past the ceiling the document can no longer be opened *and* no longer
/// be compacted, so the one operation that would bring it back under the limit
/// is gated by the limit.
///
/// Deliberately a separate function rather than an unbounded `CrdtImportLimits`
/// constructor: bytes from a peer cannot reach this path by passing a value.
pub(crate) fn admit_local_import(
    bytes: &[u8],
    current: &loro::VersionVector,
) -> Result<ImportAdmission> {
    admit_structure(bytes, current)
}

/// The checks that hold regardless of where the bytes came from: authenticated
/// metadata, and per-peer ranges that do not regress.
fn admit_structure(bytes: &[u8], current: &loro::VersionVector) -> Result<ImportAdmission> {
    let metadata = loro::LoroDoc::decode_import_blob_meta(bytes, true).map_err(|error| {
        CrdtError::ImportMalformed {
            detail: error.to_string(),
        }
    })?;
    let encoded = count_range_operations(&metadata.partial_start_vv, &metadata.partial_end_vv)?;
    let imported = count_new_operations(
        &metadata.partial_start_vv,
        &metadata.partial_end_vv,
        current,
    )?;
    Ok(ImportAdmission {
        encoded_operations: encoded,
        new_operations: imported,
    })
}

/// Count all operations carried by authenticated import metadata.
fn count_range_operations(start: &loro::VersionVector, end: &loro::VersionVector) -> Result<usize> {
    for (peer, start_counter) in start.iter() {
        let end_counter = end.get(peer).copied().unwrap_or_default();
        if end_counter < *start_counter {
            return Err(CrdtError::ImportInvalidOperationRange);
        }
    }
    end.iter().try_fold(0usize, |total, (peer, end_counter)| {
        let start_counter = start.get(peer).copied().unwrap_or_default();
        let operations = end_counter
            .checked_sub(start_counter)
            .ok_or(CrdtError::ImportInvalidOperationRange)?;
        let operations =
            usize::try_from(operations).map_err(|_| CrdtError::ImportInvalidOperationRange)?;
        total
            .checked_add(operations)
            .ok_or(CrdtError::ImportInvalidOperationRange)
    })
}

/// Count exact newly contributed operations from authenticated import metadata.
fn count_new_operations(
    start: &loro::VersionVector,
    end: &loro::VersionVector,
    current: &loro::VersionVector,
) -> Result<usize> {
    for (peer, start_counter) in start.iter() {
        let end_counter = end.get(peer).copied().unwrap_or_default();
        if end_counter < *start_counter {
            return Err(CrdtError::ImportInvalidOperationRange);
        }
    }
    end.iter().try_fold(0usize, |total, (peer, end_counter)| {
        let start_counter = start.get(peer).copied().unwrap_or_default();
        if *end_counter < start_counter {
            return Err(CrdtError::ImportInvalidOperationRange);
        }
        let current_counter = current.get(peer).copied().unwrap_or_default();
        let new_operations = if current_counter >= *end_counter {
            0
        } else {
            let new_start = start_counter.max(current_counter);
            end_counter
                .checked_sub(new_start)
                .ok_or(CrdtError::ImportInvalidOperationRange)?
        };
        let new_operations =
            usize::try_from(new_operations).map_err(|_| CrdtError::ImportInvalidOperationRange)?;
        total
            .checked_add(new_operations)
            .ok_or(CrdtError::ImportInvalidOperationRange)
    })
}
