// SPDX-License-Identifier: BUSL-1.1

//! [`ReplicatedEntry`] — the routing envelope carried alongside a
//! [`super::ReplicatedWrite`] on the Raft log, plus its (de)serialization.

use super::replicated_write::ReplicatedWrite;

/// Metadata carried alongside the write for routing on the receiving node.
#[derive(
    Debug,
    Clone,
    serde::Serialize,
    serde::Deserialize,
    zerompk::ToMessagePack,
    zerompk::FromMessagePack,
)]
pub struct ReplicatedEntry {
    pub tenant_id: u64,
    /// Database scope for the write. `0` decodes to `DatabaseId::DEFAULT`.
    ///
    /// This struct's zerompk representation is a plain positional array (no
    /// `#[msgpack(map)]`), so adding this field changed the array length from
    /// 4 to 5. An entry proposed by a not-yet-upgraded leader (still emitting
    /// the 4-element shape) would otherwise fail `check_array_len` on a new
    /// follower. `ReplicatedEntry::from_bytes` handles that case explicitly
    /// by falling back to `super::legacy_entry::LegacyReplicatedEntry` (the
    /// pre-`database_id` 4-field shape) and defaulting `database_id` to `0`.
    #[serde(default)]
    pub database_id: u64,
    pub vshard_id: u32,
    /// Per-proposal idempotency key. Generated by the proposer when the
    /// entry is constructed and embedded in the Raft log payload so the
    /// apply path can match the entry that actually committed at a given
    /// `(group_id, log_index)` against the entry the proposer is waiting
    /// for. A mismatch means a leader change overwrote the proposer's
    /// reservation with a different proposer's entry — the apply path
    /// surfaces `RetryableLeaderChange` so the gateway re-proposes.
    ///
    /// Zero is reserved as "no key" (legacy / synthetic entries that
    /// pre-date the field). The tracker treats `0` as a wildcard to
    /// preserve backwards compatibility with any in-flight log on
    /// upgrade.
    pub idempotency_key: u64,
    pub write: ReplicatedWrite,
}

impl ReplicatedEntry {
    /// Construct a new `ReplicatedEntry` with a freshly generated
    /// idempotency key. All production write paths go through this
    /// constructor; only deserialized log entries skip it (the key is
    /// preserved through `from_bytes`).
    pub fn new(tenant_id: u64, database_id: u64, vshard_id: u32, write: ReplicatedWrite) -> Self {
        // OR with 1 so the LSB is set: zero is reserved as the "no key"
        // sentinel and a fresh `rand::random::<u64>()` could in principle
        // hit zero (P ~= 2^-64 but cheap to make impossible).
        let idempotency_key = rand::random::<u64>() | 1;
        Self {
            tenant_id,
            database_id,
            vshard_id,
            idempotency_key,
            write,
        }
    }

    /// Serialize to bytes for Raft log entry data.
    pub fn to_bytes(&self) -> Vec<u8> {
        zerompk::to_msgpack_vec(self).expect("ReplicatedEntry serialization cannot fail")
    }

    /// Deserialize from Raft log entry data bytes.
    ///
    /// Tries the current 5-field shape first. If that fails specifically
    /// because the encoded array is the pre-`database_id` 4-element shape
    /// (an entry proposed by an old leader still mid-upgrade), falls back to
    /// [`super::legacy_entry::LegacyReplicatedEntry`] and defaults
    /// `database_id` to `0` (`DatabaseId::DEFAULT`). Any other decode error
    /// (corrupt data, genuinely unrelated shape) returns `None`, matching
    /// prior behavior.
    pub fn from_bytes(data: &[u8]) -> Option<Self> {
        match zerompk::from_msgpack::<Self>(data) {
            Ok(entry) => Some(entry),
            Err(zerompk::Error::ArrayLengthMismatch { actual, .. })
                if actual == super::super::legacy_entry::LegacyReplicatedEntry::FIELD_COUNT =>
            {
                zerompk::from_msgpack::<super::super::legacy_entry::LegacyReplicatedEntry>(data)
                    .ok()
                    .map(super::super::legacy_entry::LegacyReplicatedEntry::into_current)
            }
            Err(_) => None,
        }
    }
}
