-- Auto-generated by eigon-ffi-gen — DO NOT EDIT.
import Lake
open Lake DSL

package EigeniusFFI where

require EigeniusLeanCommon from git "https://github.com/eigenius/EigeniusLeanCommon.git" @ "v0.1.0"

@[default_target]
lean_lib EigeniusFFI where
  roots := #[`EigeniusFFI.Basic, `EigeniusFFI.Mirror]
