// Copyright 2026 The Eigenius Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/**
 * Locate and load the napi-rs native addon built from
 * `orchestration/runtime-substrate-native/`.
 *
 * The addon's `index.js` + `index.d.ts`
 * are generated by `napi build --platform`. We require `index.js`
 * through Node's CJS shim so Deno's Node-compat layer resolves the
 * underlying `.node` file for the platform.
 *
 * Run with Deno flags:
 *   --allow-ffi --allow-env --allow-sys --unstable-node-globals --unstable-detect-cjs
 */

import { createRequire } from "node:module";
import * as log from "../observability/mod.ts";
import { operation } from "../observability/mod.ts";

/**
 * Output of a substrate dispatch: the language runtime's output Resource
 * plus a partial `RuntimeInvocation` Resource carrying the
 * substrate-captured trace fields (numerical_metadata, started_at,
 * completed_at, image_digest, language). The orchestrator forwards
 * `output` downstream and completes / commits the partial invocation
 * with the IRIs it knows after committing the output Resource. Phase
 * 18c.5 / D26 §5.5. */
export interface DispatchOutcome {
  output: Uint8Array;
  partialInvocation: Uint8Array;
}

export interface RuntimeSubstrateAddon {
  /** Register the bash-c TestLanguageRuntime under language_id="test".
   * `workerBinaryPath` must point at the substrate crate's
   * `eigenius-test-worker` binary (e.g. `target/debug/eigenius-test-worker`). */
  registerTestLanguageRuntime(workerBinaryPath: string): void;

  /** Register the Julia language runtime under language_id="julia".
   * `workerProjectDir` points at `julia/runtime-worker/` (the directory
   * containing `Project.toml`, `Manifest.toml`, and `src/JuliaWorker.jl`).
   * `baseImageRef` is the digest-pinned Julia base image. `depotPath`
   * is the shared host/container path used for substrate artifacts —
   * must match the orchestrator's bind-mount so DooD-spawned worker
   * containers see the same path the orchestrator wrote (D26 §9.5). */
  registerJuliaLanguageRuntime(
    workerProjectDir: string,
    baseImageRef: string,
    depotPath: string,
  ): void;

  /** Register the Lean language runtime under language_id="lean".
   * `workerProjectDir` points at `lean/runtime-worker/` (the directory
   * containing `lakefile.lean`, the worker Lake project, and the
   * vendored `lean4export/` tree). `cdylibPath` is the host path to
   * `libeigenius_lean_worker.so` the worker binary dynamically links
   * against. `leanCommonDir` points at `lean/common/EigeniusLeanCommon/`
   * — the hand-authored Lake package that generated mirrors depend on;
   * staged into the image so the in-image lake-build of the mirror
   * can resolve `require EigeniusLeanCommon` offline (Phase 20a.6.x).
   * `baseImageRef` is the digest-pinned base image. `depotPath` is
   * the shared host/container path (same constraint as the Julia
   * variant). Phase 20a.5 wiring. */
  registerLeanLanguageRuntime(
    workerProjectDir: string,
    cdylibPath: string,
    leanCommonDir: string,
    baseImageRef: string,
    depotPath: string,
  ): void;

  /** Register the R language runtime under language_id="r" (D55 / D56).
   * `driverPath` points at `EigeniusRWorker.R` and `cdylibPath` at
   * `libeigenius_r_worker.so` — both baked into the R worker image; they
   * must match the recipe that built it or the boot cross-check fails
   * closed (D26 §9.3). The image is resolved per dispatch from the env
   * Resource's `image_digest`. `baseImageRef` is the digest-pinned
   * Bioconductor base. `depotPath` is the shared host/container path
   * (same constraint as the Julia/Lean variants). */
  registerRLanguageRuntime(
    driverPath: string,
    cdylibPath: string,
    baseImageRef: string,
    depotPath: string,
  ): void;

  /** Register the generic OCI tool runtime under language_id="oci" (D60).
   * `workerBinaryPath` is the host path to a pinned Eigenius worker binary
   * (e.g. `eigenius-schemaorg-worker`) staged into the orchestrator image; the
   * runtime bakes it into the tool image and computes the cross-check
   * `manifestHash` from its bytes (so the same binary must back the built
   * image, or the boot cross-check fails closed, D26 §9.3). `baseImageRef` is
   * the digest-pinned glibc base (e.g. `debian:bookworm-slim`). `depotPath` is
   * the shared host/container path (same constraint as the language variants). */
  registerOciToolRuntime(
    workerBinaryPath: string,
    baseImageRef: string,
    depotPath: string,
  ): void;

  /** Dispatch a `RunRuntimeScript` invocation. Both args are
   * Eigon-CBOR `Buffer`s; returns the output Resource and a partial
   * `RuntimeInvocation` Resource (Phase 18c.5 / D26 §5.5) carrying the
   * substrate-captured trace fields. */
  dispatchRunRuntimeScript(
    input: Uint8Array,
    argument: Uint8Array,
    additionalInputs?: Uint8Array[],
  ): Promise<DispatchOutcome>;

  /** Dispatch a `CallRuntimeMethod` invocation. v1 errors against any
   * `JobSpawner`-backed runtime — service-lifecycle envs land in
   * Phase 19a. Same outcome shape as `dispatchRunRuntimeScript`. */
  dispatchCallRuntimeMethod(
    input: Uint8Array,
    argument: Uint8Array,
  ): Promise<DispatchOutcome>;

  /** Dispatch an external-institution invocation (D31 §6.2 / Phase
   * 19a.5.c). The kernel sends the dispatch metadata as structured
   * gRPC fields rather than as a single argument Resource, so this
   * method takes them as direct parameters. `inputCbors` is the
   * multi-input list per D31 §6.5 — exactly one element for an
   * AutoOnLoad / Decidable QueryClass dispatch. Same outcome shape
   * as the script / method dispatchers. */
  dispatchExternalInstitution(
    language: string,
    envIri: string,
    imageDigest: string,
    methodName: string,
    signatureIri: string,
    inputCbors: Uint8Array[],
  ): Promise<DispatchOutcome>;

  /** Language IDs of currently-registered runtimes. */
  listRegisteredLanguages(): string[];
}

let cached: RuntimeSubstrateAddon | undefined;

/**
 * Load the native addon. Idempotent within a process.
 *
 * Throws a helpful error if the addon isn't built. The expected binary
 * lives at `orchestration/runtime-substrate-native/index.js` relative
 * to the repo root. Build it with
 * `(cd orchestration/runtime-substrate-native && ./node_modules/.bin/napi build --platform)`.
 */
export function loadRuntimeSubstrateAddon(): RuntimeSubstrateAddon {
  if (cached) return cached;

  const require = createRequire(import.meta.url);
  const addonUrl = new URL(
    "../../runtime-substrate-native/index.js",
    import.meta.url,
  );

  try {
    cached = require(addonUrl.pathname) as RuntimeSubstrateAddon;
    return cached;
  } catch (e) {
    throw new Error(
      `Failed to load runtime substrate addon at ${addonUrl.pathname}. ` +
        `Build it with: ` +
        `(cd orchestration/runtime-substrate-native && ./node_modules/.bin/napi build --platform). ` +
        `Underlying error: ${(e as Error).message}`,
    );
  }
}

/**
 * Attempt to load the addon, returning null if it isn't built. Used by
 * the orchestrator at startup so we can run without substrate support
 * — `RunRuntimeScript` / `CallRuntimeMethod` dispatches then fail with
 * a clear "no handler registered" error instead of crashing the server.
 */
export function tryLoadRuntimeSubstrateAddon(): RuntimeSubstrateAddon | null {
  try {
    return loadRuntimeSubstrateAddon();
  } catch (e) {
    log.warn(
      operation.ADDON_LOAD,
      "runtime substrate addon unavailable",
      {
        error_kind: "addon_load_failed",
        error_message: (e as Error).message.split("\n")[0],
      },
    );
    return null;
  }
}
