// Copyright 2026 The Eigenius Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! GENERATOR for the STATIVE-PARTICIPLE patch layer — the shippable importer rule, emitted as an
//! ESL layer so it can be measured WITHOUT a reseed.
//!
//! THE RULE. A verb synset whose WordNet sentence frames NAME a governed preposition also lexicalises
//! a **stative relational participle**: `associated with`, `related to`, `linked to`, `derived from`.
//! Today `convert.rs::classify` collapses 14|15|16|17|18|19|31 into one preposition-less
//! `Ditransitive` (`((S\NP)/NP)/NP`) and discards the preposition the frame names, so the relatum can
//! only ever attach as a free ADJUNCT. This emits what the rule would:
//!
//!     (S[dcl,adj]\NP)/cat_pp_arg(prep_X)   over a 2-place axiom   `wn:v{off}_rel`
//!
//! consumed by the existing `is_copula` — no new copula entry, no ontology change.
//!
//! Frame → preposition (`doc/man/wninput.5`); frame 14 is the true double-object and is EXCLUDED:
//!     15 to | 16 from | 17 with | 18 of | 19 on | 31 with
//!
//! Surfaces come from the importer's own [`past_participles`] via the same head-inflection rule, so
//! the layer is faithful to what a reseed would produce.
//!
//!     EIGENIUS_WNDICT=/path/to/WordNet-3.0/dict \
//!     EIGENIUS_STATIVE_OUT=experiments/parsing/probes/stative-participles.esl \
//!     cargo test --release -p eigenius-wordnet --test gen_stative_layer -- --ignored --nocapture

use eigenius_wordnet::inflect::past_participles;
use eigenius_wordnet::wndb::{read_data_file, Pos};
use std::path::PathBuf;

/// Frames that NAME a governed preposition. Frame 14 ("Somebody ----s somebody something") is a true
/// double-object and names none, so it is absent by design.
fn frame_prep(f: u8) -> Option<&'static str> {
    match f {
        15 => Some("to"),
        16 => Some("from"),
        17 => Some("with"),
        18 => Some("of"),
        19 => Some("on"),
        31 => Some("with"),
        _ => None,
    }
}

fn esc(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

fn head_pps(lemma: &str) -> Vec<String> {
    match lemma.split_once(' ') {
        Some((head, rest)) => past_participles(head)
            .into_iter()
            .map(|pp| format!("{pp} {rest}"))
            .collect(),
        None => past_participles(lemma),
    }
}

#[test]
#[ignore = "generator; set EIGENIUS_WNDICT + EIGENIUS_STATIVE_OUT and run --ignored --nocapture"]
fn generate_stative_participle_layer() {
    let Ok(dict) = std::env::var("EIGENIUS_WNDICT") else {
        eprintln!("EIGENIUS_WNDICT unset — skipping");
        return;
    };
    let out = std::env::var("EIGENIUS_STATIVE_OUT").expect("EIGENIUS_STATIVE_OUT");
    let data = PathBuf::from(&dict).join(Pos::Verb.data_file());
    let synsets = read_data_file(&data).expect("read data.verb");

    // Optional frame filter, so a subset can be measured on its own blast radius:
    //   EIGENIUS_STATIVE_FRAMES=17,31
    let only: Option<Vec<u8>> = std::env::var("EIGENIUS_STATIVE_FRAMES").ok().map(|v| {
        v.split(',')
            .filter_map(|t| t.trim().parse::<u8>().ok())
            .collect()
    });

    let mut buf = String::new();
    buf.push_str(
        "// GENERATED by `cargo test -p eigenius-wordnet --test gen_stative_layer` — do not hand-edit.\n\
         //\n\
         // STATIVE RELATIONAL PARTICIPLES — the shippable importer rule, as a patch layer.\n\
         // A verb synset whose WordNet frames NAME a governed preposition (15 to | 16 from | 17 with |\n\
         // 18 of | 19 on | 31 with) also lexicalises a stative participle `(S[adj]\\NP)/cat_pp_arg(prep)`\n\
         // over a 2-place axiom. Frame 14 (true double-object) is excluded. ADDITIVE: the existing\n\
         // preposition-less `Ditransitive` entries stay, so the ledger decides.\n\
         namespace core      = \"urn:eigenius:core\";\n\
         namespace epistemic = \"urn:eigenius:reflection:epistemic\";\n\
         namespace lexicon   = \"urn:eigenius:lexicon\";\n\
         namespace wn        = \"urn:eigenius:wn\";\n\n",
    );

    let (mut n_syn, mut n_entry) = (0usize, 0usize);
    for (off, syn) in &synsets {
        // One preposition per synset: the lowest-numbered naming frame, so the choice is deterministic.
        let Some(prep) = syn
            .frames
            .iter()
            .copied()
            .filter(|f| only.as_ref().is_none_or(|o| o.contains(f)))
            .filter_map(frame_prep)
            .min()
            .or_else(|| {
                syn.frames
                    .iter()
                    .copied()
                    .filter(|f| only.as_ref().is_none_or(|o| o.contains(f)))
                    .filter_map(frame_prep)
                    .next()
            })
        else {
            continue;
        };
        n_syn += 1;
        buf.push_str(&format!(
            "axiom wn:v{off}_rel : lexicon:Entity -> lexicon:Entity -> Prop desc: \"{} (stative relational participle; governs `{prep}`)\"\n\n",
            esc(&syn.gloss)
        ));
        for (i, lemma) in syn.words.iter().enumerate() {
            for (k, pp) in head_pps(lemma).iter().enumerate() {
                buf.push_str(&format!(
                    "resource wn:e_v{off}_rel_{i}_{k} : lexicon:LexicalEntry {{\n    \
                       core:description   = \"{}\";\n    \
                       lexicon:form       = \"{}\";\n    \
                       lexicon:cat        = type_expr( lexicon:fwd(lexicon:m_all, lexicon:bwd(lexicon:m_all, lexicon:cat_s(lexicon:dcl, lexicon:adj), lexicon:cat_np(lexicon:Entity, lexicon:num_any)), lexicon:cat_pp_arg(lexicon:prep_{prep})) );\n    \
                       lexicon:sem        = wn:v{off}_rel;\n    \
                       lexicon:sem_type   = type_expr( lexicon:Entity -> lexicon:Entity -> Prop );\n    \
                       lexicon:sense      = \"wn:{}.v.{off}\";\n    \
                       lexicon:grade      = epistemic:declared;\n    \
                       lexicon:in_lexicon = lexicon:wordnet;\n\
                     }}\n\n",
                    esc(&syn.gloss),
                    esc(pp),
                    lemma.replace(' ', "_"),
                ));
                n_entry += 1;
            }
        }
    }
    std::fs::write(&out, &buf).expect("write layer");
    println!("stative-participle layer: {n_syn} synsets, {n_entry} entries -> {out}");
}
