-- Auto-generated by eigon-ffi-gen — DO NOT EDIT.
import EigeniusLeanCommon

namespace EigeniusFFI

export EigeniusLeanCommon (
  EigeniusUnion
  EigenValidationError
  validateMinValueFloat
  validateMaxValueFloat
  validateMinValueInt
  validateMaxValueInt
  validateMinLength
  validateMaxLength
  validatePattern
  validateFormat
  validateOptional
  withRefinement
  withOptionalRefinement
  decodeRequiredPrim
  decodeOptionalPrim
  decodeRequiredResource
  decodeOptionalResource
  decodeRequiredPrimList
  decodeRequiredResourceList
  isAHead
)

end EigeniusFFI
